#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/rathole_server
- name: Create rathole directory
  ansible.builtin.file:
    path: /opt/rathole
    state: directory

- name: Copy rathole server config
  ansible.builtin.template:
    src: server.toml.j2
    dest: /opt/rathole/server.toml
  notify: Restart rathole server

- name: Copy docker-compose template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/rathole/docker-compose.yml
  notify: Restart rathole server

- name: Run rathole server docker-compose
  community.docker.docker_compose_v2:
    project_src: /opt/rathole
    state: present
  