#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/k3s
- name: Include prerequisites tasks
  ansible.builtin.import_tasks: kernel.yml

- name: Include firewall tasks
  ansible.builtin.import_tasks: firewall.yml

- name: Include master tasks
  ansible.builtin.import_tasks: master.yml
  when: "'k3s_masters' in group_names"

- name: Include workers tasks
  ansible.builtin.import_tasks: workers.yml
  when: "'k3s_workers' in group_names"