- name: Install docker to router nodes (edge and gateway)
  hosts: edge:gateway
  become: yes
  roles:
    - docker

- name: Install rathole to server
  hosts: edge
  become: yes
  roles:
    - rathole_server

- name: Install rathole to client
  hosts: gateway
  become: yes
  roles:
    - rathole_client