- name: Install docker to router nodes (edge and gateway)
  hosts: edge:gateway
  become: yes
  roles:
    - docker

- name: Install rathole to nodes
  hosts: edge
  become: yes
  roles:
    - rathole_server