all:
  children:
    edge:
      hosts:
        edge-1:
          ansible_host: 217.114.0.141
          ansible_user: ubuntu
    home:
      children:
        gateway:
          hosts:
            gateway-1:
              ansible_host: 192.168.1.100
              ansible_user: ubuntu
              ansible_ssh_common_args: '-o ProxyJump=ubuntu@217.114.0.141:2222'
        k3s_masters:
          hosts:
            k3s-master-1:
              ansible_host: 192.168.1.101
              ansible_user: ubuntu
              ansible_ssh_common_args: '-o ProxyJump=ubuntu@217.114.0.141:2222'
        k3s_workers:
          hosts:
            k3s-worker-1:
              ansible_host: 192.168.1.102
              ansible_user: ubuntu
              ansible_ssh_common_args: '-o ProxyJump=ubuntu@217.114.0.141:2222'
            k3s-worker-2:
              ansible_host: 192.168.1.103
              ansible_user: ubuntu
              ansible_ssh_common_args: '-o ProxyJump=ubuntu@217.114.0.141:2222'
            k3s-worker-3:
              ansible_host: 192.168.1.104
              ansible_user: ubuntu
              ansible_ssh_common_args: '-o ProxyJump=ubuntu@217.114.0.141:2222'
